# Generated by Django 4.1 on 2024-05-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iluminacion',
            name='encendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iluminacion',
            name='intensidad',
            field=models.IntegerField(default=0),
        ),
    ]
