# Generated by Django 4.1 on 2024-05-17 23:43

from django.db import migrations, models
import iluminacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacion', '0002_iluminacion_encendido_iluminacion_intensidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iluminacion',
            name='intensidad',
            field=models.IntegerField(default=0, validators=[iluminacion.models.validate_range]),
        ),
    ]
